export const ADD_POST = 'ADD_POST'
export const DELETE_POST = 'DELETE_POST'

export const INSERT_NAME = 'INSERT_NAME'
export const TOGGLE_CHANGE_NAME = 'TOGGLE_CHANGE_NAME'

export const FETCH_POST_BY_NAME = 'FETCH_POST_BY_NAME'
export const FETCH_HOME_POST = 'FETCH_HOME_POST'

export const ON_START_PROCESS = 'ON_START_PROCESS'
export const ON_STOP_PROCESS = 'ON_STOP_PROCESS'
